In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [2]:
#1.

# list_ is a list data type.
# A list can have elements of any data type.

# array_list is of array data type.
# An array can have elements of only single data type

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [3]:
#2.

print('list_ :')
for i in list_:
    print(i, '-', type(i))
    
print('array_list :')
for i in array_list:
    print(i, '-', type(i))

list_ :
1 - <class 'str'>
2 - <class 'str'>
3 - <class 'str'>
4 - <class 'str'>
5 - <class 'str'>
array_list :
1 - <class 'numpy.str_'>
2 - <class 'numpy.str_'>
3 - <class 'numpy.str_'>
4 - <class 'numpy.str_'>
5 - <class 'numpy.str_'>


In [4]:
#3.

array_list = np.array(object = list_, dtype = int)

# There will be no change in the data type of elements present in the list_.
# But there will be change in the data type of elements present in the array_list.
# All the elements of array_list are of integer type(int32).

print('list_ :')
for i in list_:
    print(i, '-', type(i))
    
print('array_list :')
for i in array_list:
    print(i, '-', type(i))

list_ :
1 - <class 'str'>
2 - <class 'str'>
3 - <class 'str'>
4 - <class 'str'>
5 - <class 'str'>
array_list :
1 - <class 'numpy.int32'>
2 - <class 'numpy.int32'>
3 - <class 'numpy.int32'>
4 - <class 'numpy.int32'>
5 - <class 'numpy.int32'>


In [5]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [6]:
#4.
print('Shape:',np.shape(num_array))
print('Size:',np.size(num_array))

Shape: (2, 3)
Size: 6


In [7]:
#5.
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
#6. 
arr2 = np.eye(5)
print(arr2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
