In [1]:
#1.

from sklearn.datasets import load_iris
X, y = load_iris(return_X_y= True)


In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.30, random_state=42)

In [3]:
from sklearn.neighbors import KNeighborsClassifier
reg = KNeighborsClassifier()
reg.fit(X_train, y_train)

KNeighborsClassifier()

In [4]:
y_pred = reg.predict(X_test)

In [5]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [6]:
#2.

# load_boston is deprecated by sklearn so using load_boston data as given on website

import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [7]:
X = data
y = target

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.30, random_state=42)

In [9]:
from sklearn.neighbors import KNeighborsRegressor
reg = KNeighborsRegressor()
reg.fit(X_train, y_train)

KNeighborsRegressor()

In [10]:
y_pred = reg.predict(X_test)

In [11]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
print(mean_squared_error(y_test, y_pred))
print(mean_absolute_error(y_test, y_pred))

30.94554736842105
4.026315789473684


In [12]:
#3.

from sklearn.datasets import load_iris
X, y = load_iris(return_X_y= True)

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.30, random_state=42)

In [14]:
from sklearn.model_selection import GridSearchCV
param = {'n_neighbors' : [1, 2 , 3, 4, 5]}

In [15]:
clf = GridSearchCV(KNeighborsClassifier() ,cv=5, param_grid=param, scoring='accuracy', verbose=3)
clf.fit(X_train, y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits
[CV 1/5] END .....................n_neighbors=1;, score=0.952 total time=   0.0s
[CV 2/5] END .....................n_neighbors=1;, score=0.952 total time=   0.0s
[CV 3/5] END .....................n_neighbors=1;, score=0.905 total time=   0.0s
[CV 4/5] END .....................n_neighbors=1;, score=1.000 total time=   0.0s
[CV 5/5] END .....................n_neighbors=1;, score=0.952 total time=   0.0s
[CV 1/5] END .....................n_neighbors=2;, score=0.905 total time=   0.0s
[CV 2/5] END .....................n_neighbors=2;, score=0.905 total time=   0.0s
[CV 3/5] END .....................n_neighbors=2;, score=0.905 total time=   0.0s
[CV 4/5] END .....................n_neighbors=2;, score=1.000 total time=   0.0s
[CV 5/5] END .....................n_neighbors=2;, score=0.952 total time=   0.0s
[CV 1/5] END .....................n_neighbors=3;, score=0.905 total time=   0.0s
[CV 2/5] END .....................n_neighbors=3;,

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5]}, scoring='accuracy',
             verbose=3)

In [16]:
clf.best_params_

{'n_neighbors': 1}

In [17]:
y_pred = clf.predict(X_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [18]:
#4.

# load_boston is deprecated by sklearn so using load_boston data as given on website

import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.30, random_state=42)

In [20]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

In [21]:
X_test = scaler.transform(X_test)

In [22]:
from sklearn.neighbors import KNeighborsRegressor
reg = KNeighborsRegressor()
reg.fit(X_train, y_train)

KNeighborsRegressor()

In [23]:
y_pred = reg.predict(X_test)

In [24]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
print(mean_squared_error(y_test, y_pred))
print(mean_absolute_error(y_test, y_pred))

0.015999999999999993
0.05333333333333332


In [25]:
#5.

from sklearn.datasets import load_iris
X, y = load_iris(return_X_y= True)


In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.30, random_state=42)

In [27]:
from sklearn.neighbors import KNeighborsClassifier
reg = KNeighborsClassifier(weights='distance')
reg.fit(X_train, y_train)

KNeighborsClassifier(weights='distance')

In [28]:
y_pred = reg.predict(X_test)

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [30]:
#6.

from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score


In [31]:
def knn_classifier_with_standardization(X_train, X_test, y_train, y_test, k_neighbors=5):
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    knn_classifier = KNeighborsClassifier(n_neighbors=k_neighbors)
    knn_classifier.fit(X_train_scaled, y_train)

    y_pred = knn_classifier.predict(X_test_scaled)

    accuracy = accuracy_score(y_test, y_pred)
    return accuracy

In [32]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [33]:
iris = load_iris()
X = iris.data
y = iris.target

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

accuracy = knn_classifier_with_standardization(X_train, X_test, y_train, y_test, k_neighbors=5)
print(accuracy)

1.0


In [35]:
#7.

def euclidean_distance(x1, y1, x2, y2):
    d = ((x1-x2)**2 + (y1-y2)**2)**0.5
    return d

In [36]:
euclidean_distance(2, 3, 3, 2)

1.4142135623730951

In [37]:
#8.

def manhattan_distance(x1, y1, x2, y2):
    d = abs(x1-x2) + abs(y1-y2)
    return d

In [38]:
manhattan_distance(2, 3, 3, 2)

2